matrix:
    include:
        - os: osx
          osx_image: xcode11
        - os: linux
          env: CC=clang CXX=clang++ npm_config_clang=1
          compiler: clang

addons:
    apt:
        packages:
            - libgnome-keyring-dev
            - icnsutils
            - graphicsmagick

sudo: true

language: node_js
node_js:
    - '13'

cache:
    timeout: 600
    directories:
        - node_modules
        - electron/node_modules
        - client/node_modules
        - $HOME/.electron

before_script:
    - sentry-cli releases set-commits "$PACKAGE_VERSION" --commit "$TRAVIS_REPO_SLUG@$TRAVIS_COMMIT"
    - sentry-cli releases new "$PACKAGE_VERSION"
after_success:
    - sentry-cli releases files "$PACKAGE_VERSION" upload-sourcemaps ./client/build/static/js/ --rewrite --url-prefix "~/dist/static/js"
    - sentry-cli releases files "$PACKAGE_VERSION" list
    - sentry-cli releases finalize "$PACKAGE_VERSION"

install:
    - npm install -g sentry-cli-binary
    - cd electron
    - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - npm install
    - cd ..
    - cd client
    - npm install
    - cd ..

script:
    - cd client
    - npm run build
    - cd ..
    - cd electron
    - npm run build
    - npm run prepare_client
    - travis_wait 80 npm run release
    - cd ..

branches:
    only:
        - master
